CFLAGS=-Wall -g

all:
	test

test:	queue.o


clean:
	rm -f test queue.o queue

  # make can't see anything in the file for object.o,
  # but it does see an object.c file,
  # and it knows how to turn a .c into a .o, so it does that.
