CFLAGS=-Wall -g

all: Mytest

Mytest:	heap.o

clean: rm -f heap.o

  # make can't see anything in the file for object.o,
  # but it does see an object.c file,
  # and it knows how to turn a .c into a .o, so it does that.
